### ISSUE TITLE
ShareX configuration generator

### ISSUE THREAD

**Issue by Lemmmy** [tmpim/shitty.dl#16]
Either generate a ShareX config and console.log it on start, or have a page which has the user type in the password, validates it and then generates it

**Comment by Wojbie** [comment]
I would suggest generating 3 configs instead of one.  One for normal upload. One for pastes and one for shortcuts. Will have to look into if import allows you to import multiple of those at time.

Also could just have it generate one on startup to "sharex.config" file and just ask user to replace "SHITTYPASSWORDHERE". that way there is no password in cleartext with some luck.

**Comment by Wojbie** [comment]
Ok so it has to be 3 separate files after all sadly. So it will require 3 
Now that i think about it user don't even have to edit files. Just ask them to change the SHITTYPASSWORDHERE value after importing. 
Here are 3 basic one i am suggesting:

```
{
  "Name": "wojbie.net images and files",
  "DestinationType": "ImageUploader, FileUploader",
  "RequestURL": "https://wojbie.net/i/upload",
  "FileFormName": "file",
  "Arguments": {
    "password": "SHITTYPASSWORDHERE"
  },
  "URL": "$json:.url$",
  "DeletionURL": "$json:.deleteUrl$"
}
```
```
{
  "Name": "wojbie.net text",
  "DestinationType": "TextUploader",
  "RequestURL": "https://wojbie.net/i/upload?paste=true",
  "FileFormName": "file",
  "Arguments": {
    "password": "SHITTYPASSWORDHERE"
  },
  "URL": "$json:.url$",
  "DeletionURL": "$json:.deleteUrl$"
}
```
```
{
  "Name": "wojbie.net ShortUrl",
  "DestinationType": "URLShortener",
  "RequestURL": "https://wojbie.net/i/upload",
  "Arguments": {
    "password": "SHITTYPASSWORDHERE",
    "link": "$input$"
  },
  "URL": "$json:.url$",
  "DeletionURL": "$json:.deleteUrl$"
}
```

Also after the imports and changing passwords user will have to change the custom uploader fields to similiar to this (URL Sharing is ignred here) :
![sharex_2018-05-20_13-58-42](https://user-images.githubusercontent.com/5893536/40278690-38ae8f12-5c36-11e8-9bbd-05d049fed339.png)

So in the end it looks like even with autogenerating of settings it will still require a bit of tutorial to get pepole working with it properly.

**Comment by Lignum** [comment]
I think having a page for this would be much nicer, since popular hosts running the software like shitty.download itself have multiple users, not all of whom have access to the server. It should only be accessible once logged in, that way we can just conveniently insert the password into the config safely.

**Comment by Lemmmy** [comment]
The reason wojbie didn't like the idea of a page is becuase he didn't think it'd fit anywhere on the site, but we recently established we could just add another row of buttons

**Comment by Wojbie** [comment]
I still don't like idea of another row of buttons but i can't squeeze another one without it looking way too busy ;D

**Comment by Wojbie** [comment]
Got started on idea. Dunno how to make navigation work nice with another page, But it works out of box if you manualy navigate to ``/misc`` page
![obraz](https://user-images.githubusercontent.com/5893536/40325943-e193182a-5d3d-11e8-9ee5-295085a67fdc.png)

**Comment by Lemmmy** [comment]
![](https://you.wouldnot.download/a-slice.png)

perhaps wrap this in [`div.action.input`](https://semantic-ui.com/elements/input.html#action) to join all the elements up?

**Comment by Wojbie** [comment]
Sure. Will do in next worthwhile commit.
Hmm I just realized this page don't need to be in menu. In can just be linked from inside the upload page.

**Comment by Wojbie** [comment]
I propose we leave this issue open for people to post example configs they would like to see added to configs page. Not like there will be any.

**Comment by Lignum** [comment]
> I propose we leave this issue open for people to post example configs they would like to see added to configs page. Not like there will be any.

I think these should be in their own issues. It would make it seem like we still don't have a ShareX configuration generator otherwise.
